api_fyp/urls.py
from django.contrib import admin
from django.urls import path, include
from .apiapp import views
from django.conf import settings 
from django.conf.urls.static import static

urlpatterns = [

    path("admin/", admin.site.urls),
    path("", views.home, name = "home"),
    path("login/", views.user_login, name = "login"),
    path("signup/", views.user_signup, name = "signup"),
    path("logout/", views.user_logout, name = "logout"),
    path("dashboard/<int:pk>/", views.dash_view, name = "dash_view"),
    path("patients/<int:pk>/", views.patients, name = "patients"),
    path("patients/add/<int:pk>/", views.patient_add_list, name = "patient_add_list"),
    path("patients/remove/<int:pk>/", views.patient_remove_list, name = "patient_remove_list"),
    path("patients/flag/<int:pk>/", views.patient_flag, name = "patient_flag"),
    path("patient_dashboard/<int:pk>/<int:p_pk>/", views.patient_dashboard, name = "patient_dashboard"),
    path("patient_dashboard/add_mri/<int:pk>/<int:p_pk>/", views.add_img, name = "add_img"),
    path("patient_dashboard/prediction_view/<int:pk>/<int:p_pk>/", views.prediction_view, name="prediction_view"),
    path("profile/<int:pk>/", views.profile, name = "profile"),
    # automatic creation of a url for image path
]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT )

users/urls.py
from django.urls import path
from .import views

urlpatterns = [
    
]

api_fyp/apiapp/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.contrib.auth.models import AbstractUser
# import that allows me to automatically create profile when user joins
from django.db.models.signals import post_save


# extending the django user profile
class User(AbstractUser):
    email = models.EmailField(unique = True)
    def __str__(self):
        return self.username
    
    def as_dict(self):
        return{
            'id': self.id,
            'password': self.password,
            'username': self.username,
            'email': self.email,
        }
# making a profile for each user 
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete= models.CASCADE)
    def __str__(self):
        return self.user.username
#  model for the patient data
class Patient(models.Model):

    # Choices for Gender 
    GenderChoices = [
        (0,'Male'),
        (1, 'Female')
    ]
    
    # Choices for Dominant Hand 
    Dominant_H_Choices = [
        (0,'Right'),
        (1, 'Left')
    ]

    PT_F_NAME = models.CharField(max_length=50, null=True, blank=False)
    PT_LAST_NAME = models.CharField(max_length=50, null=True, blank=False)
    SUBJECT_ID = models.CharField(max_length=50, null=True, blank=False, unique=True)
    GENDER = models.IntegerField(choices=GenderChoices, null=True, blank=False)
    HAND = models.IntegerField(choices=Dominant_H_Choices, null=True, blank=False)
    assigned_to = models.ForeignKey(UserProfile, on_delete=models.CASCADE, related_name= 'assigned_to',null=True, blank=True)
    flagged_by = models.ForeignKey(UserProfile, on_delete=models.CASCADE, related_name= 'flagged_by',null=True, blank=True)
    def __str__(self):
        return self.SUBJECT_ID
# model for stored visits 
class Visit(models.Model):

    # Choices for Social Economic Status 
    CDR_Choices = [
        (0,'Non Demented'),
        (0.5, 'Very Mild AD'),
        (1, 'Mild AD'),
        (2, 'Moderate AD'),
    ]

    # Chices got Group
    Group_Choices = [
        (0,'Non Demented'),
        (1, 'Demented'),
        (2, 'Converted')
    ] 
    # maximum 6 visits for now 
    GROUP = models.IntegerField(choices=Group_Choices , null=True, blank=False)
    VISIT = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)],null=True, blank=False)
    EDUCATION = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(100)],null=True, blank=False)
    SES = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)],null=True, blank=False)
    CDR = models.FloatField(choices=CDR_Choices, null=True, blank=False)
    MMSCORE = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(30)],null=True, blank=False)
    AGE = models.IntegerField(validators=[MinValueValidator(0)],null=True, blank=False)
    ETIV = models.FloatField(validators=[MinValueValidator(0)],null=True, blank=False)
    NWBV = models.FloatField(validators=[MinValueValidator(0)],null=True, blank=False)
    ASF = models.FloatField(validators=[MinValueValidator(0)],null=True, blank=False)
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE, related_name= 'visits',null=False, blank=True)

    def __str__(self):
        return str(self.id)
# predictions are stored within this model once made, keeping a log of previous predictions
class Prediction(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE, related_name= 'prediction',null=True, blank=True)
    Prediction_Result = models.JSONField(null=True, blank=True)
    Risk_prediction = models.CharField(max_length =100,null=True, blank =True)
    # Prediction_Result = models.CharField(max_length =100,null=True, blank=False)
    DATE_PREDICTED = models.DateTimeField(null=True, blank=False)

    def __str__(self):
        return str(self.id)
# mri images are saved in this model  
class MRI_IMG(models.Model):
    patient_img = models.ForeignKey(Patient, on_delete=models.CASCADE, related_name= 'MRI_image',null=True, blank=True)
    # on image upload media dir and imgs sub dir created
    MRI_ID = models.CharField(max_length=50, null=True, blank=False, unique=True)
    img = models.ImageField(null=True, blank=True,upload_to='imgs/')
    def __str__(self):
        return str(self.id)
# function creates a new user using the instance passed into it 
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        profile = UserProfile(user=instance)
        profile.save()
post_save.connect(create_user_profile, sender = User)

api_fyp/apiapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Patient
from .models import UserProfile
from django.contrib import messages 
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.forms import AuthenticationForm
from .forms import create_user
from .forms import edit_user
from .forms import create_new_patient
from .models import Visit
from .forms import create_visit
from django.http import JsonResponse
import pandas as pd
from google.oauth2 import service_account
import google.auth.transport.requests
from sklearn.preprocessing import MinMaxScaler
import json
import requests
import re
import json
import numpy as np
import requests
from django.utils import timezone
from google.auth import load_credentials_from_file
from google.auth.transport.requests import Request
from django.http import HttpResponse, HttpRequest, JsonResponse
from .models import Prediction
import datetime
from django.core.serializers import serialize
from django.template.loader import render_to_string
from django.db.models import Q
from .forms import create_MRI
from django.contrib.auth.models import User


# rendering the home page 
def home(request: HttpRequest) -> HttpResponse:
    return render(request, 'Home.html', {})
# rendering the profile page with the user information
def profile(request: HttpRequest, pk) -> HttpResponse:
    user_info = get_object_or_404(UserProfile, id=pk)
    if request.method == "GET":
        form = edit_user(instance=user_info.user)
        return render(request, 'Profile.html', {"user_info": user_info, "form": form})
    if request.method =="POST":
        form = edit_user(request.POST or None, instance = user_info.user)
        if form.is_valid():
            form.save();
        return render(request, 'Profile.html', {"user_info": user_info, "form": form})
    

def userprofile(request: HttpRequest, pk) -> HttpResponse:
    if request.user.is_authenticated:
        user_info = get_object_or_404(UserProfile, id=pk)
        return JsonResponse({"user_info" : user_info})
    else:
        messages.success(request, ("please login to view"))
        return redirect('login')


# using django's inbuilt authenticate function to process the post form
def user_login(request: HttpRequest) -> HttpResponse:
    # getting the login page 
    if request.method == "GET":
        return render(request, 'login.html')
    # andling submission
    elif request.method == "POST":
        username = request.POST['user_username']
        password = request.POST['user_password']
        user = authenticate(request,username= username, password = password)
        if user is not None:
            login(request, user)
            return redirect('dash_view', pk=user.pk)
    else: 
        return JsonResponse({'error': "login not successful"})

def user_logout(request):
    logout(request)
    return redirect('home')

def user_signup(request):
    if request.method =='GET':
        form = create_user()
        return render(request, 'signup.html', {'form': form})
    if request.method == 'POST':
        form = create_user(request.POST)
        if form.is_valid():
            user_form = form.save(commit=False)
            # user_form.username = user_form.username.lower()
            password_n = form.cleaned_data.get('password1')
            user_form.save()
            user = authenticate(username = user_form.username, password= password_n)
            login(request, user)
            return redirect('dash_view', pk=user.pk)
    return JsonResponse({'error': "signup not successful"})
# patient rendering view 
def patients(request, pk):
    # form to add patients 
    user_info = get_object_or_404(UserProfile, id=pk)
    query = request.GET.get('query_value')
    # search handling get and post requests
    if query:
        query = query.split()
        fields = Q()
        for i in query:
            fields |= Q(PT_F_NAME__icontains= i)
            fields |= Q(PT_LAST_NAME__icontains= i)
            fields |= Q(SUBJECT_ID__icontains= i)
        patients = Patient.objects.filter(fields)
        patients_list = list(patients.values())
    else:
        patients = Patient.objects.filter(assigned_to__isnull = True)
        patients_list = list(patients.values())
    if request.method == 'GET':
        form = create_new_patient()
        if request.headers.get('X-Requested-With')== 'XMLHttpRequest' and request.GET.get('action') == 'get_form':
            form_b = render_to_string('patient.html', {'form':form}, request)
            return JsonResponse({'form': form_b})
        return render(request,'patients.html', {
            'patients': patients_list,
            'user_info': user_info , 
            'form': form
        })
    # creating new patient view handling get and post requests
    elif request.method == 'POST'and request.headers.get('X-Requested-With') == 'XMLHttpRequest':
        form = create_new_patient(request.POST)
        if form.is_valid():
            patient = form.save()
            form = create_new_patient()
            # return redirect('patients', pk = patient.pk)
        # patients = Patient.objects.filter(assigned_to__isnull = True)
        # patients_list = list(patients.values())
        return JsonResponse({
            "patients": patients_list,
            'id': patient.id,
            'SUBJECT_ID': patient.SUBJECT_ID,
            'MRI_ID': patient.MRI_ID, 
            'GENDER': patient.GENDER, 
            'HAND':patient.HAND
        })
    else:
       form = create_new_patient( request.POST)
       if form.is_valid():
            patient = form.save()
            return redirect('patients', pk=pk )

    # only patients that are not already assigned show up
    return render(request, 'patients.html', {'user_info': user_info, 'form':create_new_patient(), "patients": patients_list})
# redners the assigned/ flagged patients on the main dashbaord 
def dash_view(request, pk):
    if request.user.is_authenticated:
        try:
            user_info = get_object_or_404(UserProfile, id=pk)
            profile = UserProfile.objects.get(user=request.user)
            current_patients = Patient.objects.filter(assigned_to = profile)
            flagged_patients = Patient.objects.filter(flagged_by=profile)
            print(flagged_patients, profile)
            return render(request, "dashboard.html", {"current_patients" : current_patients, "user_info" : user_info, "flagged_patients" : flagged_patients})
        except:
                current_patients = Patient.objects.none()
                flagged_patients = Patient.objects.none()
    else:
       current_patients= Patient.objects.none()
       flagged_patients = Patient.objects.none()
    
    return render(request, "dashboard.html", {"current_patients" : current_patients, "user_info" : user_info , "flagged_patients" : flagged_patients})
# saves an instance of a patient to the database
def patient_add_list(request, pk):
    add_patient = Patient.objects.get(pk=pk)
    profile = UserProfile.objects.get(user=request.user)
    add_patient.assigned_to = profile
    add_patient.save()
    return redirect('patients', pk=profile.pk)
# handles get and post requests for creating visits on the patient dashbaord 
def patient_dashboard(request, pk , p_pk):
    patient_info = get_object_or_404(Patient, id=p_pk)
    user_info = get_object_or_404(UserProfile, id=pk)
    patient_visits = Visit.objects.filter(patient = patient_info).order_by('VISIT')
    prediction_patient = Prediction.objects.filter(patient = patient_info).order_by('DATE_PREDICTED').last()
    current_diagnosis = Visit.objects.filter(patient = patient_info).order_by('VISIT').last()
    if request.method == 'GET':
        form = create_visit()
        form_mri = create_MRI()
        if request.headers.get('X-Requested-With')== 'XMLHttpRequest' and request.GET.get('action') == 'get_form':
            form_b = render_to_string('patient_dashboard.html', {'form':form}, request)
            return JsonResponse({'form': form_b})
        return render(request, 'patient_dashboard.html', {'form': form, 'form_mri': form_mri, 'patient_info': patient_info,'user_info': user_info,'patient_visits': patient_visits ,"predictions": prediction_patient,"current_diagnosis":current_diagnosis})
    elif request.method == 'POST' and request.headers.get('X-Requested-With') == 'XMLHttpRequest':
        form = create_visit(request.POST)
        if form.is_valid():
            visit_form = form.save(commit=False)
            visit_form.patient = patient_info
            form.save()
            form = create_visit() 
            # prediction = None
        else:
            print("no valid ")
        patient_visits_list = list(patient_visits.values())
        return JsonResponse({
            "patient_visits": patient_visits_list
        })
    else:
       form = create_visit(request.POST)
       if form.is_valid():
            visit_form = form.save(commit=False)
            visit_form.patient = patient_info
            form.save()
            return redirect('patient_dashboard', pk=pk, p_pk =p_pk )
       else:
            return render(request, 'patient_dashboard.html', {'form': form,'form_mri' :form_mri,  'patient_info': patient_info,'user_info': user_info,'patient_visits': patient_visits ,"predictions": prediction_patient,"current_diagnosis":current_diagnosis})
# handles the get and post request for the mri image upload form, saving an instance in the database 
def add_img(request, pk , p_pk):
    patient_info = get_object_or_404(Patient, id=p_pk)
    user_info = get_object_or_404(UserProfile, id=pk)
    patient_visits = Visit.objects.filter(patient = patient_info).order_by('VISIT')
    prediction_patient = Prediction.objects.filter(patient = patient_info).order_by('DATE_PREDICTED').last()
    current_diagnosis = Visit.objects.filter(patient = patient_info).order_by('VISIT').last()
    if request.method == 'GET':
        form = create_MRI()

api_fyp/apiapp/templates/patient_dashboard.html
{% extends 'base.html' %}

{% block content %}
  <div class="modal fade" id="Modal_add_visit" tabindex="-1" aria-labelledby="Modal_add_visitLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
            <!-- modal form for adding patients triggered by the button in the containiner, allows users to add visits -->
          <h1 class="modal-title fs-5" id="Modal_add_visitLabel">ADD VISIT RESULTS</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div id = "modal_container" class="modal-body">
            <form method = "post" id = "form_visit" action="{% url 'patient_dashboard' pk=user_info.pk  p_pk=patient_info.id %}"  novalidate>
                {% csrf_token%}
                {{form.as_p}}
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary">Save changes</button>
                </div>
            </form>
        </div>
      </div>
    </div>
  </div>
  <!-- allows users to upload images and store them locally using a modal form -->
  <div class="modal fade" id="Modal_add_img" tabindex="-1" aria-labelledby="Modal_add_imgLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="Modal_add_imgLabel">MRI IMAGES RESULTS</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div id = "modal_container" class="modal-body">
            <form method = "post" enctype="multipart/form-data" id = "form_img" action="{% url 'add_img' pk=user_info.pk  p_pk=patient_info.id %}"  novalidate>
                {% csrf_token%}
                {{form_mri.as_p}}
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary">UPLOAD</button>
                </div>
            </form>
        </div>
      </div>
    </div>
  </div>
  <!-- the main patient dashboard -->
<div class="patient_dash">
    <!-- <br></br> -->
     <!-- patient information and flag button displayed here -->
    <div class="patient">
        <a href="{% url 'dash_view' pk=user.pk %}" class="btn" id="back_button">
            <i class= "bi bi-arrow-left" style=" filter: invert(1);"></i>
        </a>
        <h1 id="patient_name"> {{ patient_info.PT_F_NAME }}  {{ patient_info.PT_LAST_NAME }}</h1>
        <a href="{%url 'patient_flag' pk=patient_info.id %}" class="btn" id="flag">FLAG</a>
    </div>
   <!-- the health overview for the selected patient -->
    <br></br>
    <div class="title">
        <h2 id="title"> HEALTH OVERVIEW</h2>
    </div>
    <br></br>
    <div class="container" >
        <div class="container2">
            <!-- once the prediction is made through the button the current risk is updated -->
            <div  class = "container_risk">
                <div class="prediction_title">
                    <div>
                        <h3>AD CURRENT RISK</h3>
                    </div>
                    <div>
                        <a href="{%url 'prediction_view' pk=user_info.id p_pk=patient_info.id %}" class="btn btn-primary" id="predictor">PREDICT</a>
                    </div>    
                </div>
                <!-- gets prediction stored in the database, once prediction is generated it is stored in the database and displayed to the user -->
                <div class="risk_prediction">
                    {%if predictions%}
                    <p>{{predictions.Risk_prediction}}</p>
                    {%else%}
                    <p>Not enough visits</p>
                    {%endif%}
                </div>
            </div>
            <br></br>
            <!-- displays the most recent diagnosis if there are predictions -->
            <div class = "container_diag">
                <div>
                    <h3>CURRENT DIAGNOSIS</h3>
                </div>
                <div class="Diagnoisis">
                    {%if predictions%}
                    <p>{{current_diagnosis.get_GROUP_display}}</p>
                    {%else%}
                    <p>Not enough visits</p>
                    {%endif%}
                </div>
            </div>
            <br></br>
            <div class = "container_MRI">
                <div class="mri">
                    <a id = "add_mri" href="{% url 'add_img' pk=user_info.pk  p_pk=patient_info.id %}" data-bs-toggle="modal"  data-bs-target="#Modal_add_img" class="btn btn-primary">ADD MRI</a>
                </div>
            </div>
        </div>
        <!-- contains all the visits associated witht the user in the form of a table -->
        <div  class = "container_visits">
            <div class = "visit_header">
                <div>
                    <h3>VISITS</h3>
                </div>
          
                <div>
                    <a id = "add_patient" href="{% url 'patient_dashboard' pk=user_info.pk  p_pk=patient_info.id %}" data-bs-toggle="modal"  data-bs-target="#Modal_add_visit" class="btn btn-primary">ADD VISIT</a>
            </div>
            </div>
            <div class="visits">
                <table>
                    <thead>
                        <tr>
                            <th scope="col">VISIT</th>
                            <th scope="col">GROUP</th>
                            <th scope="col">EDUC</th>
                            <th scope="col">SES</th>
                            <th scope="col">CDR</th>
                            <th scope="col">MMSCORE</th>
                            <th scope="col">AGE</th>
                            <th scope="col">ETIV</th>
                            <th scope="col">NWBW</th>
                            <th scope="col">ASF</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for visit in patient_visits %}
                        <tr>
                            <td>{{visit.VISIT}}</td>
                            <td>{{visit.GROUP}}</td>
                            <td>{{visit.EDUCATION}}</td>
                            <td>{{visit.SES}}</td>
                            <td>{{visit.CDR}}</td>
                            <td>{{visit.MMSCORE}}</td>
                            <td>{{visit.AGE}}</td>
                            <td>{{visit.ETIV}}</td>
                            <td>{{visit.NWBV}}</td>
                            <td>{{visit.ASF}}</td>
                        </tr>
                        {% endfor %} 
                    </tbody>
                   </table>
                </div>
            </div>
        </div>
        </div>
    </div>
</div>
<script>
const form_visit = document.getElementById('form_visit');
  
  if (form_visit) {
    form_visit.addEventListener('submit', function(event) {
      event.preventDefault();
      const formData = new FormData(this);
      fetch(this.action, {
        method: "POST",
        body: formData,
        headers: {'X-Requested-With': 'XMLHttpRequest','X-CSRFToken': formData.get('csrfmiddlewaretoken')}
      })
      .then(response => response.json())
      .then(data =>{
        if (data.patient_visits) {
          window.location.reload();
        } 
        else {
          alert('saveING ERROR');
        }
      })
      .catch(error => {console.error('CANT SUBMIT FORM', error);});
    });
  }

</script>
<style>
#back_button{
    width: 4rem ; 
    height: 3rem;
    font-size: 1.5rem; 
    border-radius: 0.5rem;
    display: flex; 
    align-items: center;
    justify-content: center;
}

#back_button{
    background-color: #0077ff;
}
table{
    max-width: 30rem; 
}

#patient_name{
    box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
}
.container_diag{
    gap:1rem;
    padding: 1rem; 
    display:flex; 
    align-items: center; 
    flex-direction:column;
    min-width: 10rem; 
    min-height: 10rem; 
    justify-content : center ; 
    border: 0.05rem solid rgba(0, 0, 0, 0); 
    border-radius: 1rem; 
    overflow: hidden; 
    box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
    background-color: white;
}
.patient{
    display: flex; 
    justify-content: space-between;
}
.patient_dash{
    min-width: 100rem;
}
/* #title{

} */
.title{
    color: #0077ff; 
    border-radius: 1rem; 
    padding: 1rem; 
    width: 100%;
    display: flex; 
    justify-content:center; 
    background-color: rgba(255, 255, 255, 0.77); 
    align-items: center;
    box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
} 
h1{
    font-size: 2rem; 
    overflow: hidden; 
    background-color: rgba(255, 255, 255, 0.77); 
    color: rgb(82, 82, 82); border-radius: 1rem; 
    padding: 1rem; 
    width: 80%; 
    display: flex; 
    justify-content: center;
}

h2{
    font-size: 2rem; 
    overflow: hidden;
}
#flag{
    width: 10%;
    height: 20%;
    font-size: 1.5rem;
    background-color: red; 
    color: white; 
    display: flex; 
    justify-content: center;
}
h3{
    font-size: 1rem; 
    display:flex; 
    align-items: center; 
    color:  #0077ff; 
}
#edit_button{
    background-color:rgba(0, 187, 0, 0.69); 
    width: 3rem ; 
    height: 3rem;
    font-size: 1.5rem; 
    border-radius: 0.5rem;
    display: flex; 
    align-items: center;
}
.container{
    display: flex; 
    flex-direction: row; 
    justify-content: space-between;

    gap: 5rem;
}
.container2{
    display:flex; 
    justify-content: space-between; 
    flex-direction: column;
}
.container_risk{
    box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
    padding: 1rem; 
    display:flex; 
    align-items: center; 
    flex-direction:column; 
    min-width: 20rem; 
    min-height: 10rem; 
    justify-content : center ; 
    border: 0.05rem solid rgba(0, 0, 0, 0); 
    border-radius: 1rem; 
    overflow: hidden; 
    background-color: white;
}
.container_MRI{
    box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
    padding: 1rem; 
    display:flex; 
    align-items: center; 
    flex-direction:column; 
    min-width: 20rem; 
    min-height: 10rem; 
    justify-content : center ; 
    border: 0.05rem solid rgba(0, 0, 0, 0); 
    border-radius: 1rem; 
    overflow: hidden; 
    background-color: white;
}
.prediction_title{
    padding: 1rem;
    display:flex; 
    align-items: center; 
    flex-direction:row; 
    gap: 2rem;
}
#predictor{
    font-size: 0.7rem;
}
.risk_prediction{
    position:relative; 
    width: 80%;
    height: 4rem; 
    margin:0.5rem auto; 
    display:flex; 
    align-items: center; 
    flex-direction:column;
}
         
.Diagnosis{
    position:relative; 
    width: 80%; 
    height: 4rem; 
    margin:0.5rem auto;
}

.container_visits{
    padding: 1rem; 
    display:flex; 
    align-items: center; 
    flex-direction:column;  
    min-width: 75rem; 
    min-height: 35rem; 
    justify-content : center ; 
    border: 0.05rem solid rgba(0, 0, 0, 0);
    border-radius: 1rem; 
    overflow-x: scroll; 
    overflow-y: scroll; 
    background-color: white;
    box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
}
.visit_header{
    padding: 0.5rem 3rem 0.5rem  0.5rem;
    position:relative; 
    top: -13rem; 
    left:9rem; 
    display:flex; 
    justify-content:center;  
    flex-direction: row; 
    gap:15rem;
}
        
#add_patient{
    font-size: 0.7rem;
}
.visits{
    position:relative; 
    width: 80%;
    max-width: 80%; 
    height: 4rem; 
    right: 4rem; 
    top: -12rem; 
    text-overflow: ellipsis;
} 
table, tr, td, th{
  border: 1px solid #ddd;
  padding: 0.5rem 3rem 0.5rem  0.5rem;
}
.modal-content{
    border-radius: 1rem;
}
#Modal_add_visitLabel{
    font-size: 3rem;
}



</style>


{% endblock%}